webtalk_init -webtalk_dir C:/Users/13372/Documents/GitHub/VHDL_Digital_Systems_Design_Examples/UART_TX_Example/UART_TX/UART_TX.sim/sim_1/behav/xsim/xsim.dir/UART_TOP_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 14 19:40:49 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8c3f959b-16dc-4135-bee5-002cde41f505" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d5d86177a3b149dda29133beb42f23d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1498 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "45105 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7084_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3358824013 -regid "" -xml C:/Users/13372/Documents/GitHub/VHDL_Digital_Systems_Design_Examples/UART_TX_Example/UART_TX/UART_TX.sim/sim_1/behav/xsim/xsim.dir/UART_TOP_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/13372/Documents/GitHub/VHDL_Digital_Systems_Design_Examples/UART_TX_Example/UART_TX/UART_TX.sim/sim_1/behav/xsim/xsim.dir/UART_TOP_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/13372/Documents/GitHub/VHDL_Digital_Systems_Design_Examples/UART_TX_Example/UART_TX/UART_TX.sim/sim_1/behav/xsim/xsim.dir/UART_TOP_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
