set_property SRC_FILE_INFO {cfile:C:/Users/13372/Documents/GitHub/VHDL_Digital_Systems_Design_Examples/UART_TX_Example/UART_TX/UART_TX.srcs/constrs_1/new/UART_Master.xdc rfile:../../../UART_TX.srcs/constrs_1/new/UART_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btnC]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports RsTx]
